<?php

function load_color_field( $field ) {

    if(strpos($field['name'], 'background_color') !== false) {
        $field['choices'] = array(
            'none' => 'None',
            'red' => 'Red',
            'dark-blue' => 'Blue',
            'white' => 'White',
            'lila' => 'Lila',
        );
    }

    return $field;

}

add_filter('acf/load_field', 'load_color_field');


// if( function_exists('acf_add_local_field_group') ):
//
// acf_add_local_field_group(array (
// 	'key' => 'group_573a1fcd0e3db',
// 	'title' => 'Front-page info',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_575081c8d26fb',
// 			'label' => 'Icons',
// 			'name' => 'icons',
// 			'type' => 'repeater',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'collapsed' => '',
// 			'min' => 5,
// 			'max' => 5,
// 			'layout' => 'table',
// 			'button_label' => 'Add Row',
// 			'sub_fields' => array (
// 				array (
// 					'key' => 'field_575081dbd26fc',
// 					'label' => 'Icon',
// 					'name' => 'icon',
// 					'type' => 'image',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'return_format' => 'array',
// 					'preview_size' => 'thumbnail',
// 					'library' => 'all',
// 					'min_width' => '',
// 					'min_height' => '',
// 					'min_size' => '',
// 					'max_width' => '',
// 					'max_height' => '',
// 					'max_size' => '',
// 					'mime_types' => '',
// 				),
// 				array (
// 					'key' => 'field_5750820ad26fd',
// 					'label' => 'Title',
// 					'name' => 'title',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 					'readonly' => 0,
// 					'disabled' => 0,
// 				),
// 			),
// 		),
// 		array (
// 			'key' => 'field_5750826fd26ff',
// 			'label' => 'Icons link',
// 			'name' => 'icons_link',
// 			'type' => 'page_link',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 		),
// 		array (
// 			'key' => 'field_57508286d2700',
// 			'label' => 'Icons button text',
// 			'name' => 'icons_button_text',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'page_template',
// 				'operator' => '==',
// 				'value' => 'front-page.php',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_5737a0cc013a0',
// 	'title' => 'General page elements',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_5737a0d1b6790',
// 			'label' => 'Tagline',
// 			'name' => 'tagline',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_5737a0f8b6791',
// 			'label' => 'Description',
// 			'name' => 'description',
// 			'type' => 'textarea',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'maxlength' => '',
// 			'rows' => '',
// 			'new_lines' => 'br',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_5737a118b6792',
// 			'label' => 'Link',
// 			'name' => 'link',
// 			'type' => 'text',
// 			'instructions' => 'Only internal pages. No first slash.',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 'ventures/autolab',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_5737a12bb6793',
// 			'label' => 'Link title',
// 			'name' => 'link_title',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => 30,
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_573c9bb2e8877',
// 			'label' => 'Promo 1',
// 			'name' => 'promo_1',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'promos',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 		array (
// 			'key' => 'field_573c9bfce8878',
// 			'label' => 'Promo 2',
// 			'name' => 'promo_2',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'promos',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'post',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'page',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'seeds',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'ventures',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'acf_after_title',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => 'These will only show up if you also set a featured image.',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_572beced5aab9',
// 	'title' => 'Job info',
// 	'fields' => array (
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'page_template',
// 				'operator' => '==',
// 				'value' => 'template-jobs.php',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'side',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_573cb6f392800',
// 	'title' => 'Personal story info',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_573cb6f857abf',
// 			'label' => 'Team member',
// 			'name' => 'team_member',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'team_members',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 		array (
// 			'key' => 'field_573cb70f57ac0',
// 			'label' => 'Story',
// 			'name' => 'story',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'sliders',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'personal_stories',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_573a241a5c0b9',
// 	'title' => 'Promo info',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_575075f4ced1c',
// 			'label' => 'Type',
// 			'name' => 'type',
// 			'type' => 'select',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'choices' => array (
// 				'Promo' => 'Promo',
// 				'Statistic' => 'Statistic',
// 				'Quote' => 'Quote',
// 			),
// 			'default_value' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'ui' => 0,
// 			'ajax' => 0,
// 			'placeholder' => '',
// 			'disabled' => 0,
// 			'readonly' => 0,
// 		),
// 		array (
// 			'key' => 'field_573a247b313c2',
// 			'label' => 'Description',
// 			'name' => 'description',
// 			'type' => 'textarea',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'maxlength' => '',
// 			'rows' => '',
// 			'new_lines' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_573a241e887ff',
// 			'label' => 'Link',
// 			'name' => 'link',
// 			'type' => 'page_link',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 		),
// 		array (
// 			'key' => 'field_573a243c88800',
// 			'label' => 'Button text',
// 			'name' => 'button_text',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => 'Read more',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_57507636ced1d',
// 			'label' => 'Team member',
// 			'name' => 'team_member',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => array (
// 				array (
// 					array (
// 						'field' => 'field_575075f4ced1c',
// 						'operator' => '==',
// 						'value' => 'Quote',
// 					),
// 				),
// 			),
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'team_members',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'promos',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_572bea3acc3c2',
// 	'title' => 'Seed info',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_572bea485ae33',
// 			'label' => 'Year',
// 			'name' => 'year',
// 			'type' => 'number',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 2015,
// 			'prepend' => '',
// 			'append' => '',
// 			'min' => 2000,
// 			'max' => 2050,
// 			'step' => 1,
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_573c9a6d1533b',
// 			'label' => 'Story',
// 			'name' => 'story',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'sliders',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'seeds',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_573b83d5bab2d',
// 	'title' => 'Slider',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_573b83e2cad47',
// 			'label' => 'Slider',
// 			'name' => 'slider',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'sliders',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'page_template',
// 				'operator' => '==',
// 				'value' => 'template-about.php',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'page_template',
// 				'operator' => '==',
// 				'value' => 'template-team_members.php',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_5737c60fcc4a3',
// 	'title' => 'Slider info',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_57520926a139b',
// 			'label' => 'type',
// 			'name' => 'type',
// 			'type' => 'select',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'choices' => array (
// 				'team members' => 'team members',
// 				'personal story' => 'personal story',
// 			),
// 			'default_value' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'ui' => 0,
// 			'ajax' => 0,
// 			'placeholder' => '',
// 			'disabled' => 0,
// 			'readonly' => 0,
// 		),
// 		array (
// 			'key' => 'field_5737c62744cb5',
// 			'label' => 'Slides',
// 			'name' => 'slides',
// 			'type' => 'repeater',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'collapsed' => '',
// 			'min' => 1,
// 			'max' => '',
// 			'layout' => 'table',
// 			'button_label' => 'Add Row',
// 			'sub_fields' => array (
// 				array (
// 					'key' => 'field_5737c64a44cb6',
// 					'label' => 'Title',
// 					'name' => 'title',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 					'readonly' => 0,
// 					'disabled' => 0,
// 				),
// 				array (
// 					'key' => 'field_5737c65544cb7',
// 					'label' => 'Description',
// 					'name' => 'description',
// 					'type' => 'textarea',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'maxlength' => '',
// 					'rows' => '',
// 					'new_lines' => 'br',
// 					'readonly' => 0,
// 					'disabled' => 0,
// 				),
// 				array (
// 					'key' => 'field_5737c66244cb8',
// 					'label' => 'Image',
// 					'name' => 'image',
// 					'type' => 'image',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'return_format' => 'url',
// 					'preview_size' => 'thumbnail',
// 					'library' => 'all',
// 					'min_width' => '',
// 					'min_height' => '',
// 					'min_size' => '',
// 					'max_width' => '',
// 					'max_height' => '',
// 					'max_size' => '',
// 					'mime_types' => '',
// 				),
// 			),
// 		),
// 		array (
// 			'key' => 'field_5737c69044cb9',
// 			'label' => 'Background image',
// 			'name' => 'background_image',
// 			'type' => 'image',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'return_format' => 'url',
// 			'preview_size' => 'thumbnail',
// 			'library' => 'all',
// 			'min_width' => '',
// 			'min_height' => '',
// 			'min_size' => '',
// 			'max_width' => '',
// 			'max_height' => '',
// 			'max_size' => '',
// 			'mime_types' => '',
// 		),
// 		array (
// 			'key' => 'field_5737c802bf0a7',
// 			'label' => 'Slides in view',
// 			'name' => 'slides_in_view',
// 			'type' => 'number',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => 1,
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'min' => 1,
// 			'max' => 5,
// 			'step' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'sliders',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_572bd90f4512f',
// 	'title' => 'Team member info',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_572bd9462c756',
// 			'label' => 'Job Title',
// 			'name' => 'job_title',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 'Managing Partner',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => 40,
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_572bd9df2c757',
// 			'label' => 'Email',
// 			'name' => 'email',
// 			'type' => 'email',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 'you@venture.com',
// 			'prepend' => '',
// 			'append' => '',
// 		),
// 		array (
// 			'key' => 'field_572bda152c758',
// 			'label' => 'LinkedIn',
// 			'name' => 'linkedin',
// 			'type' => 'url',
// 			'instructions' => 'It\'s important to use the public url of LinkedIn.',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 'http://co.linkedin.com/pub/wenyi-cai/6/987/5a9',
// 		),
// 		array (
// 			'key' => 'field_572bda6a2c759',
// 			'label' => 'Description',
// 			'name' => 'description',
// 			'type' => 'textarea',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'maxlength' => '',
// 			'rows' => '',
// 			'new_lines' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_572bdb792c75b',
// 			'label' => 'Start Year',
// 			'name' => 'start_year',
// 			'type' => 'number',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 2015,
// 			'prepend' => '',
// 			'append' => '',
// 			'min' => 2000,
// 			'max' => 2050,
// 			'step' => 1,
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_572bdbaf2c75c',
// 			'label' => 'End Year',
// 			'name' => 'end_year',
// 			'type' => 'number',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 2016,
// 			'prepend' => '',
// 			'append' => '',
// 			'min' => 2000,
// 			'max' => 2050,
// 			'step' => 1,
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'team_members',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_572be7208ee5c',
// 	'title' => 'Venture info',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_572be83539ab8',
// 			'label' => 'Website',
// 			'name' => 'website',
// 			'type' => 'url',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 'www.venture.com',
// 		),
// 		array (
// 			'key' => 'field_572be85339ab9',
// 			'label' => 'Email',
// 			'name' => 'email',
// 			'type' => 'email',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 'info@venture.com',
// 			'prepend' => '',
// 			'append' => '',
// 		),
// 		array (
// 			'key' => 'field_572be86739aba',
// 			'label' => 'Seed',
// 			'name' => 'seed',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'seeds',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'id',
// 			'ui' => 1,
// 		),
// 		array (
// 			'key' => 'field_5737c5ecca233',
// 			'label' => 'Milestones',
// 			'name' => 'milestones',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'sliders',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'ventures',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_572be150274aa',
// 	'title' => 'Ventures',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_572be1553ab04',
// 			'label' => 'Ventures',
// 			'name' => 'ventures',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'ventures',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 1,
// 			'return_format' => 'id',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'team_members',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'post',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'promos',
// 			),
// 		),
// 	),
// 	'menu_order' => 1,
// 	'position' => 'side',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_572be6578a7cc',
// 	'title' => 'Seeds',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_572be65a5f6ea',
// 			'label' => 'Seeds',
// 			'name' => 'seeds',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'seeds',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 1,
// 			'return_format' => 'id',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'team_members',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'promos',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'post',
// 			),
// 		),
// 	),
// 	'menu_order' => 3,
// 	'position' => 'side',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// endif;