<?php

function load_select_options( $field ) {

    if(strpos($field['name'], 'background_color') !== false) {
        $field['choices'] = array(
            'none text-dark' => 'None',
            'red text-white' => 'Red',
            'aqua text-white' => 'Aqua',
            'dark-blue text-white' => 'Blue',
            'white' => 'White',
            'lila text-white' => 'Lila',
        );
    } else if(strpos($field['name'], 'title_size') !== false) {
        $field['choices'] = array(
            'normal' => 'Normal',
            'big' => 'Big',
            'extra-big' => 'Extra big',
            'huge' => 'Huge',
        );
    }

    return $field;

}

add_filter('acf/load_field', 'load_select_options');

// if( function_exists('acf_add_local_field_group') ):
//
// acf_add_local_field_group(array (
// 	'key' => 'group_57560f0aa7f02',
// 	'title' => 'Page builder',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_57560f0e5a3e3',
// 			'label' => 'Content',
// 			'name' => 'content',
// 			'type' => 'flexible_content',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'button_label' => 'Add block',
// 			'min' => '',
// 			'max' => '',
// 			'layouts' => array (
// 				array (
// 					'key' => '57560f14a2912',
// 					'name' => 'full_width_image',
// 					'label' => 'Full width image',
// 					'display' => 'block',
// 					'sub_fields' => array (
// 						array (
// 							'key' => 'field_575621775a3e5',
// 							'label' => 'Background image',
// 							'name' => 'background_image',
// 							'type' => 'image',
// 							'instructions' => '',
// 							'required' => 1,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'return_format' => 'array',
// 							'preview_size' => 'thumbnail',
// 							'library' => 'all',
// 							'min_width' => '',
// 							'min_height' => '',
// 							'min_size' => '',
// 							'max_width' => '',
// 							'max_height' => '',
// 							'max_size' => '',
// 							'mime_types' => '',
// 						),
// 						array (
// 							'key' => 'field_5756228c5a3eb',
// 							'label' => 'Alignment',
// 							'name' => 'alignment',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 1,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'col-md-6' => 'Left',
// 								'col-md-6 col-md-offset-3 text-center' => 'Center',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_5756221e5a3ea',
// 							'label' => 'Overlay color',
// 							'name' => 'overlay_color',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'none' => 'None',
// 								'overlay-red text-white' => 'Red',
// 								'overlay-dark-blue text-white' => 'Blue',
// 								'overlay-aqua text-white' => 'Aqua',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_575621a15a3e6',
// 							'label' => 'Title',
// 							'name' => 'title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_575860528d9a8',
// 							'label' => 'Title size',
// 							'name' => 'title_size',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'normal' => 'Normal',
// 								'big' => 'Big',
// 								'extra-big' => 'Extra big',
// 								'huge' => 'Huge',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_575621b75a3e7',
// 							'label' => 'Text',
// 							'name' => 'text',
// 							'type' => 'textarea',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'maxlength' => '',
// 							'rows' => '',
// 							'new_lines' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_575621cd5a3e8',
// 							'label' => 'Button text',
// 							'name' => 'button_text',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_575621e45a3e9',
// 							'label' => 'Button link',
// 							'name' => 'button_link',
// 							'type' => 'page_link',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'post_type' => array (
// 							),
// 							'taxonomy' => array (
// 							),
// 							'allow_null' => 1,
// 							'multiple' => 0,
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
// 				array (
// 					'key' => '575621695a3e4',
// 					'name' => 'posts',
// 					'label' => 'Posts',
// 					'display' => 'block',
// 					'sub_fields' => array (
// 						array (
// 							'key' => 'field_5757240196b64',
// 							'label' => 'Title',
// 							'name' => 'title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_5757240f96b65',
// 							'label' => 'Sub title',
// 							'name' => 'sub_title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_5756e82d2822f',
// 							'label' => 'Background color',
// 							'name' => 'background_color',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'none' => 'None',
// 								'red' => 'Red',
// 								'dark-blue' => 'Blue',
// 								'white' => 'White',
// 								'lila' => 'Lila',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_575622ed5a3ec',
// 							'label' => 'Post type',
// 							'name' => 'post_type',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'posts' => 'posts',
// 								'promos' => 'promos',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_5756dbd83f79c',
// 							'label' => 'Filter',
// 							'name' => 'filter',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => array (
// 								array (
// 									array (
// 										'field' => 'field_575622ed5a3ec',
// 										'operator' => '!=',
// 										'value' => 'posts',
// 									),
// 								),
// 							),
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'type' => 'type',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_5756dbf23f79d',
// 							'label' => 'Value',
// 							'name' => 'value',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => array (
// 								array (
// 									array (
// 										'field' => 'field_575622ed5a3ec',
// 										'operator' => '!=',
// 										'value' => 'posts',
// 									),
// 								),
// 							),
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'statistic' => 'statistic',
// 								'quote' => 'quote',
// 								'promo' => 'promo',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_5756d7cc9e6b4',
// 							'label' => 'Maximum posts',
// 							'name' => 'maximum_posts',
// 							'type' => 'number',
// 							'instructions' => '-1 for all',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => -1,
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'min' => '',
// 							'max' => '',
// 							'step' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_575623cf5a3ed',
// 							'label' => 'Show images',
// 							'name' => 'show_images',
// 							'type' => 'true_false',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'message' => '',
// 							'default_value' => 1,
// 						),
// 						array (
// 							'key' => 'field_575623f05a3ee',
// 							'label' => 'Post title size',
// 							'name' => 'post_title_size',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'normal' => 'Normal',
// 								'big' => 'Big',
// 								'extra-big' => 'Extra big',
// 								'huge' => 'Huge',
// 							),
// 							'default_value' => array (
// 								0 => 'normal',
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_575625f95a3f3',
// 							'label' => 'Button text',
// 							'name' => 'button_text',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_575626055a3f4',
// 							'label' => 'Button link',
// 							'name' => 'button_link',
// 							'type' => 'page_link',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'post_type' => array (
// 							),
// 							'taxonomy' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
// 				array (
// 					'key' => '575624165a3ef',
// 					'name' => 'slider',
// 					'label' => 'Slider',
// 					'display' => 'block',
// 					'sub_fields' => array (
// 						array (
// 							'key' => 'field_575723be96b62',
// 							'label' => 'Title',
// 							'name' => 'title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_575723d296b63',
// 							'label' => 'Sub title',
// 							'name' => 'sub_title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_5756e8152822e',
// 							'label' => 'Background color',
// 							'name' => 'background_color',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'none' => 'None',
// 								'red' => 'Red',
// 								'dark-blue' => 'Blue',
// 								'white' => 'White',
// 								'lila' => 'Lila',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_575624525a3f0',
// 							'label' => 'Type',
// 							'name' => 'type',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'team' => 'Team',
// 								'personal_story' => 'Personal story',
// 								'timeline' => 'Timeline',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_575624945a3f1',
// 							'label' => 'Category',
// 							'name' => 'category',
// 							'type' => 'post_object',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => array (
// 								array (
// 									array (
// 										'field' => 'field_575624525a3f0',
// 										'operator' => '==',
// 										'value' => 'team',
// 									),
// 								),
// 							),
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'post_type' => array (
// 								0 => 'ventures',
// 								1 => 'seeds',
// 							),
// 							'taxonomy' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'return_format' => 'object',
// 							'ui' => 1,
// 						),
// 						array (
// 							'key' => 'field_575625395a3f2',
// 							'label' => 'Slider',
// 							'name' => 'slider',
// 							'type' => 'post_object',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => array (
// 								array (
// 									array (
// 										'field' => 'field_575624525a3f0',
// 										'operator' => '!=',
// 										'value' => 'team',
// 									),
// 								),
// 							),
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'post_type' => array (
// 								0 => 'sliders',
// 							),
// 							'taxonomy' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'return_format' => 'object',
// 							'ui' => 1,
// 						),
// 						array (
// 							'key' => 'field_5756f05328230',
// 							'label' => 'Height',
// 							'name' => 'height',
// 							'type' => 'number',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'min' => 100,
// 							'max' => 500,
// 							'step' => 100,
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_5756f0ee28231',
// 							'label' => 'Slides in view',
// 							'name' => 'slides_in_view',
// 							'type' => 'number',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => 1,
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'min' => 1,
// 							'max' => 10,
// 							'step' => 1,
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_575626165a3f5',
// 							'label' => 'Button text',
// 							'name' => 'button_text',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_575626255a3f6',
// 							'label' => 'Button link',
// 							'name' => 'button_link',
// 							'type' => 'page_link',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'post_type' => array (
// 							),
// 							'taxonomy' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
// 				array (
// 					'key' => '575626a05a3f7',
// 					'name' => 'icons',
// 					'label' => 'Icons',
// 					'display' => 'block',
// 					'sub_fields' => array (
// 						array (
// 							'key' => 'field_5756e4ac09c8b',
// 							'label' => 'Title',
// 							'name' => 'title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_5756e4b709c8c',
// 							'label' => 'Sub title',
// 							'name' => 'sub_title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_5756e50653315',
// 							'label' => 'Background color',
// 							'name' => 'background_color',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'none' => 'None',
// 								'red' => 'Red',
// 								'dark-blue' => 'Blue',
// 								'white' => 'White',
// 								'lila' => 'Lila',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_575626ba5a3f8',
// 							'label' => 'Icons',
// 							'name' => 'icons',
// 							'type' => 'repeater',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'collapsed' => '',
// 							'min' => 2,
// 							'max' => 6,
// 							'layout' => 'table',
// 							'button_label' => 'Add Row',
// 							'sub_fields' => array (
// 								array (
// 									'key' => 'field_575626eb5a3f9',
// 									'label' => 'Image',
// 									'name' => 'image',
// 									'type' => 'image',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array (
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'preview_size' => 'thumbnail',
// 									'min_width' => '',
// 									'min_height' => '',
// 									'min_size' => '',
// 									'max_width' => '',
// 									'max_height' => '',
// 									'max_size' => '',
// 									'mime_types' => '',
// 									'return_format' => 'array',
// 									'library' => 'all',
// 								),
// 								array (
// 									'key' => 'field_575627045a3fa',
// 									'label' => 'Text',
// 									'name' => 'text',
// 									'type' => 'text',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array (
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'default_value' => '',
// 									'placeholder' => '',
// 									'prepend' => '',
// 									'append' => '',
// 									'maxlength' => '',
// 									'readonly' => 0,
// 									'disabled' => 0,
// 								),
// 								array (
// 									'key' => 'field_575627295a3fd',
// 									'label' => 'Link',
// 									'name' => 'link',
// 									'type' => 'page_link',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array (
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'post_type' => array (
// 									),
// 									'taxonomy' => array (
// 									),
// 									'allow_null' => 0,
// 									'multiple' => 0,
// 								),
// 							),
// 						),
// 						array (
// 							'key' => 'field_575627145a3fb',
// 							'label' => 'Button text',
// 							'name' => 'button_text',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_5756271e5a3fc',
// 							'label' => 'Button link',
// 							'name' => 'button_link',
// 							'type' => 'page_link',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'post_type' => array (
// 							),
// 							'taxonomy' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
// 				array (
// 					'key' => '575627735a3fe',
// 					'name' => 'promos',
// 					'label' => 'Promos',
// 					'display' => 'block',
// 					'sub_fields' => array (
// 						array (
// 							'key' => 'field_57573ef9879a0',
// 							'label' => 'Title',
// 							'name' => 'title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_57573f05879a1',
// 							'label' => 'Sub title',
// 							'name' => 'sub_title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_57573f0d879a2',
// 							'label' => 'Background color',
// 							'name' => 'background_color',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'none' => 'None',
// 								'red' => 'Red',
// 								'dark-blue' => 'Blue',
// 								'white' => 'White',
// 								'lila' => 'Lila',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_575627865a3ff',
// 							'label' => 'Promo 1',
// 							'name' => 'promo_1',
// 							'type' => 'post_object',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'post_type' => array (
// 								0 => 'promos',
// 							),
// 							'taxonomy' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'return_format' => 'object',
// 							'ui' => 1,
// 						),
// 						array (
// 							'key' => 'field_575719ff5d5fe',
// 							'label' => 'Promo 1 background color',
// 							'name' => 'promo_1_background_color',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'none' => 'None',
// 								'red' => 'Red',
// 								'dark-blue' => 'Blue',
// 								'white' => 'White',
// 								'lila' => 'Lila',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_575627975a400',
// 							'label' => 'Promo 2',
// 							'name' => 'promo_2',
// 							'type' => 'post_object',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'post_type' => array (
// 								0 => 'promos',
// 							),
// 							'taxonomy' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'return_format' => 'object',
// 							'ui' => 1,
// 						),
// 						array (
// 							'key' => 'field_57571bd45d5ff',
// 							'label' => 'Promo 2 background color',
// 							'name' => 'promo_2_background_color',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'none' => 'None',
// 								'red' => 'Red',
// 								'dark-blue' => 'Blue',
// 								'white' => 'White',
// 								'lila' => 'Lila',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_57573f6d879a6',
// 							'label' => 'Button text',
// 							'name' => 'button_text',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_57573f70879a7',
// 							'label' => 'Button link',
// 							'name' => 'button_link',
// 							'type' => 'page_link',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'post_type' => array (
// 							),
// 							'taxonomy' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
// 				array (
// 					'key' => '5756282f5a401',
// 					'name' => 'team_matrix',
// 					'label' => 'Team matrix',
// 					'display' => 'block',
// 					'sub_fields' => array (
// 						array (
// 							'key' => 'field_57573f41879a3',
// 							'label' => 'Title',
// 							'name' => 'title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_57573f45879a4',
// 							'label' => 'Sub title',
// 							'name' => 'sub_title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_57573f49879a5',
// 							'label' => 'Background color',
// 							'name' => 'background_color',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'none' => 'None',
// 								'red' => 'Red',
// 								'dark-blue' => 'Blue',
// 								'white' => 'White',
// 								'lila' => 'Lila',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_5756292b5a402',
// 							'label' => 'Category',
// 							'name' => 'category',
// 							'type' => 'post_object',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'post_type' => array (
// 								0 => 'ventures',
// 								1 => 'seeds',
// 							),
// 							'taxonomy' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'return_format' => 'object',
// 							'ui' => 1,
// 						),
// 						array (
// 							'key' => 'field_57573f8c879a8',
// 							'label' => 'Button text',
// 							'name' => 'button_text',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_57573f9d879aa',
// 							'label' => 'Button link',
// 							'name' => 'button_link',
// 							'type' => 'page_link',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'post_type' => array (
// 							),
// 							'taxonomy' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
// 				array (
// 					'key' => '57575695b1e88',
// 					'name' => 'simple_text',
// 					'label' => 'Simple text',
// 					'display' => 'block',
// 					'sub_fields' => array (
// 						array (
// 							'key' => 'field_57575695b1e89',
// 							'label' => 'Title',
// 							'name' => 'title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_57575695b1e8a',
// 							'label' => 'Sub title',
// 							'name' => 'sub_title',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_57575695b1e8b',
// 							'label' => 'Background color',
// 							'name' => 'background_color',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'none' => 'None',
// 								'red' => 'Red',
// 								'dark-blue' => 'Blue',
// 								'white' => 'White',
// 								'lila' => 'Lila',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_575756b9b1e8f',
// 							'label' => 'Text',
// 							'name' => 'text',
// 							'type' => 'textarea',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'maxlength' => '',
// 							'rows' => '',
// 							'new_lines' => 'br',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_575756e5b1e90',
// 							'label' => 'Alignment',
// 							'name' => 'alignment',
// 							'type' => 'select',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'choices' => array (
// 								'text-left' => 'Left',
// 								'text-center' => 'Center',
// 								'text-right' => 'Right',
// 							),
// 							'default_value' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 							'ui' => 0,
// 							'ajax' => 0,
// 							'placeholder' => '',
// 							'disabled' => 0,
// 							'readonly' => 0,
// 						),
// 						array (
// 							'key' => 'field_57575735b1e91',
// 							'label' => 'Width',
// 							'name' => 'width',
// 							'type' => 'number',
// 							'instructions' => 'Number of columns. 2 smallest, 12 biggest.',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'min' => 2,
// 							'max' => 12,
// 							'step' => 2,
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_57575695b1e8d',
// 							'label' => 'Button text',
// 							'name' => 'button_text',
// 							'type' => 'text',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'default_value' => '',
// 							'placeholder' => '',
// 							'prepend' => '',
// 							'append' => '',
// 							'maxlength' => '',
// 							'readonly' => 0,
// 							'disabled' => 0,
// 						),
// 						array (
// 							'key' => 'field_57575695b1e8e',
// 							'label' => 'Button link',
// 							'name' => 'button_link',
// 							'type' => 'page_link',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'post_type' => array (
// 							),
// 							'taxonomy' => array (
// 							),
// 							'allow_null' => 0,
// 							'multiple' => 0,
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
// 				array (
// 					'key' => '57575b1a91d1c',
// 					'name' => 'tabs',
// 					'label' => 'Tabs',
// 					'display' => 'block',
// 					'sub_fields' => array (
// 						array (
// 							'key' => 'field_57575cb444417',
// 							'label' => 'Tabs',
// 							'name' => 'tabs',
// 							'type' => 'repeater',
// 							'instructions' => '',
// 							'required' => 0,
// 							'conditional_logic' => 0,
// 							'wrapper' => array (
// 								'width' => '',
// 								'class' => '',
// 								'id' => '',
// 							),
// 							'collapsed' => '',
// 							'min' => 2,
// 							'max' => 6,
// 							'layout' => 'table',
// 							'button_label' => 'Add Row',
// 							'sub_fields' => array (
// 								array (
// 									'key' => 'field_57575d9a44419',
// 									'label' => 'icon',
// 									'name' => 'icon',
// 									'type' => 'image',
// 									'instructions' => '',
// 									'required' => 1,
// 									'conditional_logic' => 0,
// 									'wrapper' => array (
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'return_format' => 'array',
// 									'preview_size' => 'thumbnail',
// 									'library' => 'all',
// 									'min_width' => '',
// 									'min_height' => '',
// 									'min_size' => '',
// 									'max_width' => '',
// 									'max_height' => '',
// 									'max_size' => '',
// 									'mime_types' => '',
// 								),
// 								array (
// 									'key' => 'field_575b23a63bb59',
// 									'label' => 'Image',
// 									'name' => 'image',
// 									'type' => 'image',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array (
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'return_format' => 'array',
// 									'preview_size' => 'thumbnail',
// 									'library' => 'all',
// 									'min_width' => '',
// 									'min_height' => '',
// 									'min_size' => '',
// 									'max_width' => '',
// 									'max_height' => '',
// 									'max_size' => '',
// 									'mime_types' => '',
// 								),
// 								array (
// 									'key' => 'field_575b250d31191',
// 									'label' => 'Image height',
// 									'name' => 'image_height',
// 									'type' => 'number',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array (
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'default_value' => '',
// 									'placeholder' => '',
// 									'prepend' => '',
// 									'append' => '',
// 									'min' => 50,
// 									'max' => 500,
// 									'step' => '',
// 									'readonly' => 0,
// 									'disabled' => 0,
// 								),
// 								array (
// 									'key' => 'field_57575df74441c',
// 									'label' => 'Text',
// 									'name' => 'text',
// 									'type' => 'textarea',
// 									'instructions' => '',
// 									'required' => 1,
// 									'conditional_logic' => 0,
// 									'wrapper' => array (
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'default_value' => '',
// 									'placeholder' => '',
// 									'maxlength' => '',
// 									'rows' => '',
// 									'new_lines' => 'br',
// 									'readonly' => 0,
// 									'disabled' => 0,
// 								),
// 								array (
// 									'key' => 'field_575b252b31192',
// 									'label' => 'Background color',
// 									'name' => 'background_color',
// 									'type' => 'text',
// 									'instructions' => '',
// 									'required' => 0,
// 									'conditional_logic' => 0,
// 									'wrapper' => array (
// 										'width' => '',
// 										'class' => '',
// 										'id' => '',
// 									),
// 									'default_value' => '',
// 									'placeholder' => '',
// 									'prepend' => '',
// 									'append' => '',
// 									'maxlength' => '',
// 									'readonly' => 0,
// 									'disabled' => 0,
// 									'choices' => array (
// 										'none' => 'None',
// 										'red' => 'Red',
// 										'dark-blue' => 'Blue',
// 										'white' => 'White',
// 										'lila' => 'Lila',
// 									),
// 								),
// 							),
// 						),
// 					),
// 					'min' => '',
// 					'max' => '',
// 				),
// 			),
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'page',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'acf_after_title',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => array (
// 		0 => 'the_content',
// 		1 => 'excerpt',
// 		2 => 'custom_fields',
// 		3 => 'discussion',
// 		4 => 'comments',
// 		5 => 'revisions',
// 		6 => 'slug',
// 		7 => 'author',
// 		8 => 'format',
// 		9 => 'page_attributes',
// 		10 => 'featured_image',
// 		11 => 'send-trackbacks',
// 	),
// 	'active' => 1,
// 	'description' => '',
// ));
//
// endif;


// if( function_exists('acf_add_local_field_group') ):
//
// acf_add_local_field_group(array (
// 	'key' => 'group_573a1fcd0e3db',
// 	'title' => 'Front-page info',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_575081c8d26fb',
// 			'label' => 'Icons',
// 			'name' => 'icons',
// 			'type' => 'repeater',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'collapsed' => '',
// 			'min' => 5,
// 			'max' => 5,
// 			'layout' => 'table',
// 			'button_label' => 'Add Row',
// 			'sub_fields' => array (
// 				array (
// 					'key' => 'field_575081dbd26fc',
// 					'label' => 'Icon',
// 					'name' => 'icon',
// 					'type' => 'image',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'return_format' => 'array',
// 					'preview_size' => 'thumbnail',
// 					'library' => 'all',
// 					'min_width' => '',
// 					'min_height' => '',
// 					'min_size' => '',
// 					'max_width' => '',
// 					'max_height' => '',
// 					'max_size' => '',
// 					'mime_types' => '',
// 				),
// 				array (
// 					'key' => 'field_5750820ad26fd',
// 					'label' => 'Title',
// 					'name' => 'title',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 					'readonly' => 0,
// 					'disabled' => 0,
// 				),
// 			),
// 		),
// 		array (
// 			'key' => 'field_5750826fd26ff',
// 			'label' => 'Icons link',
// 			'name' => 'icons_link',
// 			'type' => 'page_link',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 		),
// 		array (
// 			'key' => 'field_57508286d2700',
// 			'label' => 'Icons button text',
// 			'name' => 'icons_button_text',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'page_template',
// 				'operator' => '==',
// 				'value' => 'front-page.php',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_5737a0cc013a0',
// 	'title' => 'General page elements',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_5737a0d1b6790',
// 			'label' => 'Tagline',
// 			'name' => 'tagline',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_5737a0f8b6791',
// 			'label' => 'Description',
// 			'name' => 'description',
// 			'type' => 'textarea',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'maxlength' => '',
// 			'rows' => '',
// 			'new_lines' => 'br',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_5737a118b6792',
// 			'label' => 'Link',
// 			'name' => 'link',
// 			'type' => 'text',
// 			'instructions' => 'Only internal pages. No first slash.',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 'ventures/autolab',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_5737a12bb6793',
// 			'label' => 'Link title',
// 			'name' => 'link_title',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => 30,
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_573c9bb2e8877',
// 			'label' => 'Promo 1',
// 			'name' => 'promo_1',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'promos',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 		array (
// 			'key' => 'field_573c9bfce8878',
// 			'label' => 'Promo 2',
// 			'name' => 'promo_2',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'promos',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'post',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'page',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'seeds',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'ventures',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'acf_after_title',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => 'These will only show up if you also set a featured image.',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_572beced5aab9',
// 	'title' => 'Job info',
// 	'fields' => array (
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'page_template',
// 				'operator' => '==',
// 				'value' => 'template-jobs.php',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'side',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_573cb6f392800',
// 	'title' => 'Personal story info',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_573cb6f857abf',
// 			'label' => 'Team member',
// 			'name' => 'team_member',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'team_members',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 		array (
// 			'key' => 'field_573cb70f57ac0',
// 			'label' => 'Story',
// 			'name' => 'story',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'sliders',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'personal_stories',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_573a241a5c0b9',
// 	'title' => 'Promo info',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_575075f4ced1c',
// 			'label' => 'Type',
// 			'name' => 'type',
// 			'type' => 'select',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'choices' => array (
// 				'Promo' => 'Promo',
// 				'Statistic' => 'Statistic',
// 				'Quote' => 'Quote',
// 			),
// 			'default_value' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'ui' => 0,
// 			'ajax' => 0,
// 			'placeholder' => '',
// 			'disabled' => 0,
// 			'readonly' => 0,
// 		),
// 		array (
// 			'key' => 'field_573a247b313c2',
// 			'label' => 'Description',
// 			'name' => 'description',
// 			'type' => 'textarea',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'maxlength' => '',
// 			'rows' => '',
// 			'new_lines' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_573a241e887ff',
// 			'label' => 'Link',
// 			'name' => 'link',
// 			'type' => 'page_link',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 		),
// 		array (
// 			'key' => 'field_573a243c88800',
// 			'label' => 'Button text',
// 			'name' => 'button_text',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => 'Read more',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_57507636ced1d',
// 			'label' => 'Team member',
// 			'name' => 'team_member',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => array (
// 				array (
// 					array (
// 						'field' => 'field_575075f4ced1c',
// 						'operator' => '==',
// 						'value' => 'Quote',
// 					),
// 				),
// 			),
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'team_members',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'promos',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_572bea3acc3c2',
// 	'title' => 'Seed info',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_572bea485ae33',
// 			'label' => 'Year',
// 			'name' => 'year',
// 			'type' => 'number',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 2015,
// 			'prepend' => '',
// 			'append' => '',
// 			'min' => 2000,
// 			'max' => 2050,
// 			'step' => 1,
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_573c9a6d1533b',
// 			'label' => 'Story',
// 			'name' => 'story',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'sliders',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'seeds',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_573b83d5bab2d',
// 	'title' => 'Slider',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_573b83e2cad47',
// 			'label' => 'Slider',
// 			'name' => 'slider',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'sliders',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'page_template',
// 				'operator' => '==',
// 				'value' => 'template-about.php',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'page_template',
// 				'operator' => '==',
// 				'value' => 'template-team_members.php',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_5737c60fcc4a3',
// 	'title' => 'Slider info',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_57520926a139b',
// 			'label' => 'type',
// 			'name' => 'type',
// 			'type' => 'select',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'choices' => array (
// 				'team members' => 'team members',
// 				'personal story' => 'personal story',
// 			),
// 			'default_value' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'ui' => 0,
// 			'ajax' => 0,
// 			'placeholder' => '',
// 			'disabled' => 0,
// 			'readonly' => 0,
// 		),
// 		array (
// 			'key' => 'field_5737c62744cb5',
// 			'label' => 'Slides',
// 			'name' => 'slides',
// 			'type' => 'repeater',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'collapsed' => '',
// 			'min' => 1,
// 			'max' => '',
// 			'layout' => 'table',
// 			'button_label' => 'Add Row',
// 			'sub_fields' => array (
// 				array (
// 					'key' => 'field_5737c64a44cb6',
// 					'label' => 'Title',
// 					'name' => 'title',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 					'readonly' => 0,
// 					'disabled' => 0,
// 				),
// 				array (
// 					'key' => 'field_5737c65544cb7',
// 					'label' => 'Description',
// 					'name' => 'description',
// 					'type' => 'textarea',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'maxlength' => '',
// 					'rows' => '',
// 					'new_lines' => 'br',
// 					'readonly' => 0,
// 					'disabled' => 0,
// 				),
// 				array (
// 					'key' => 'field_5737c66244cb8',
// 					'label' => 'Image',
// 					'name' => 'image',
// 					'type' => 'image',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array (
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'return_format' => 'url',
// 					'preview_size' => 'thumbnail',
// 					'library' => 'all',
// 					'min_width' => '',
// 					'min_height' => '',
// 					'min_size' => '',
// 					'max_width' => '',
// 					'max_height' => '',
// 					'max_size' => '',
// 					'mime_types' => '',
// 				),
// 			),
// 		),
// 		array (
// 			'key' => 'field_5737c69044cb9',
// 			'label' => 'Background image',
// 			'name' => 'background_image',
// 			'type' => 'image',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'return_format' => 'url',
// 			'preview_size' => 'thumbnail',
// 			'library' => 'all',
// 			'min_width' => '',
// 			'min_height' => '',
// 			'min_size' => '',
// 			'max_width' => '',
// 			'max_height' => '',
// 			'max_size' => '',
// 			'mime_types' => '',
// 		),
// 		array (
// 			'key' => 'field_5737c802bf0a7',
// 			'label' => 'Slides in view',
// 			'name' => 'slides_in_view',
// 			'type' => 'number',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => 1,
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'min' => 1,
// 			'max' => 5,
// 			'step' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'sliders',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_572bd90f4512f',
// 	'title' => 'Team member info',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_572bd9462c756',
// 			'label' => 'Job Title',
// 			'name' => 'job_title',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 'Managing Partner',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => 40,
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_572bd9df2c757',
// 			'label' => 'Email',
// 			'name' => 'email',
// 			'type' => 'email',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 'you@venture.com',
// 			'prepend' => '',
// 			'append' => '',
// 		),
// 		array (
// 			'key' => 'field_572bda152c758',
// 			'label' => 'LinkedIn',
// 			'name' => 'linkedin',
// 			'type' => 'url',
// 			'instructions' => 'It\'s important to use the public url of LinkedIn.',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 'http://co.linkedin.com/pub/wenyi-cai/6/987/5a9',
// 		),
// 		array (
// 			'key' => 'field_572bda6a2c759',
// 			'label' => 'Description',
// 			'name' => 'description',
// 			'type' => 'textarea',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'maxlength' => '',
// 			'rows' => '',
// 			'new_lines' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_572bdb792c75b',
// 			'label' => 'Start Year',
// 			'name' => 'start_year',
// 			'type' => 'number',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 2015,
// 			'prepend' => '',
// 			'append' => '',
// 			'min' => 2000,
// 			'max' => 2050,
// 			'step' => 1,
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array (
// 			'key' => 'field_572bdbaf2c75c',
// 			'label' => 'End Year',
// 			'name' => 'end_year',
// 			'type' => 'number',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 2016,
// 			'prepend' => '',
// 			'append' => '',
// 			'min' => 2000,
// 			'max' => 2050,
// 			'step' => 1,
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'team_members',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_572be7208ee5c',
// 	'title' => 'Venture info',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_572be83539ab8',
// 			'label' => 'Website',
// 			'name' => 'website',
// 			'type' => 'url',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 'www.venture.com',
// 		),
// 		array (
// 			'key' => 'field_572be85339ab9',
// 			'label' => 'Email',
// 			'name' => 'email',
// 			'type' => 'email',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => 'info@venture.com',
// 			'prepend' => '',
// 			'append' => '',
// 		),
// 		array (
// 			'key' => 'field_572be86739aba',
// 			'label' => 'Seed',
// 			'name' => 'seed',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 1,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'seeds',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'id',
// 			'ui' => 1,
// 		),
// 		array (
// 			'key' => 'field_5737c5ecca233',
// 			'label' => 'Milestones',
// 			'name' => 'milestones',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'sliders',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 0,
// 			'return_format' => 'object',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'ventures',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_572be150274aa',
// 	'title' => 'Ventures',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_572be1553ab04',
// 			'label' => 'Ventures',
// 			'name' => 'ventures',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'ventures',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 1,
// 			'return_format' => 'id',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'team_members',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'post',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'promos',
// 			),
// 		),
// 	),
// 	'menu_order' => 1,
// 	'position' => 'side',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// acf_add_local_field_group(array (
// 	'key' => 'group_572be6578a7cc',
// 	'title' => 'Seeds',
// 	'fields' => array (
// 		array (
// 			'key' => 'field_572be65a5f6ea',
// 			'label' => 'Seeds',
// 			'name' => 'seeds',
// 			'type' => 'post_object',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array (
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'post_type' => array (
// 				0 => 'seeds',
// 			),
// 			'taxonomy' => array (
// 			),
// 			'allow_null' => 0,
// 			'multiple' => 1,
// 			'return_format' => 'id',
// 			'ui' => 1,
// 		),
// 	),
// 	'location' => array (
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'team_members',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'promos',
// 			),
// 		),
// 		array (
// 			array (
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'post',
// 			),
// 		),
// 	),
// 	'menu_order' => 3,
// 	'position' => 'side',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => 1,
// 	'description' => '',
// ));
//
// endif;